### ISSUE TITLE
Updated functions for updated Claddis

### ISSUE THREAD

**Issue by tiago-simoes** [stjohn/hsj#1]
Hello Dr. St. John,

I'm trying to run your example codes for morphological data sets with missing data to infer phylogenies using the HSJ distance metric, but it seems that the functions are out of date because of the recent updates on the Claddis package. The function names in Claddis have changed and this seems to be affecting your hsjTS function. When I run it using your provided examples, I get the following:

> hsjTS(t1, phy4.3, mor4.3, typ4.3, alpha = 0.5)
Error in newClad$Matrix_1$Matrix[c1, j] : subscript out of bounds
Called from: initialInternalLabels(tree, clad, nTaxa, numNodes)

Do you have an updated code for your functions?

Best regards,

Tiago

**Comment by lschmitz** [comment]
Hi, Dr. St. John-

Is it possible that the names of the Claddis functions have changed again? I was trying to run the example script and got an error when PostorderEdges was called:

`> hsjTS(firstTree, madPhy, madDat, madTyp, alpha = 0)
Error in PostorderEdges(cbind(parent, child)) : 
  could not find function "PostorderEdges"`

If you have an updated version, I would love to try it out.

Thanks!
Lars
